baseURL = "https://git.timmo.xyz/home-panel"
publishDir = "../docs"
languageCode = "en-gb"
title = "Home Panel"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

[params]
	# General information
	author = "Timmo"
	description = "A touch-compatible web-app for controlling the home"
	copyright = "Released under the MIT license"

  # Repository
	provider = "GitHub"
	repo_url = "https://github.com/timmo001/home-panel"

	logo = "static/logo.svg"
	favicon = "static/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "cyan"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

[social]
	github  = "timmo001"

[[menu.main]]
	name   = "Home Panel"
	url    = "/"
	weight = 10

[[menu.main]]
	identifier = "setup"
	name   = "Setup"
	url    = "setup/"
	weight = 20

[[menu.main]]
	parent = "setup"
	name   = "Docker Compose"
	url    = "setup/docker-compose/"
	weight = 30

[[menu.main]]
	parent = "setup"
	name   = "Docker"
	url    = "setup/docker/"
	weight = 40

[[menu.main]]
	parent = "setup"
	name   = "NodeJS"
	url    = "setup/node-js/"
	weight = 50

[[menu.main]]
	identifier = "configuration"
	name   = "Configuration"
	url    = "configuration/"
	weight = 60

[[menu.main]]
	parent = "configuration"
	name   = "Starter Template"
	url    = "configuration/starter/"
	weight = 70

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 90
