---
trigger:
  batch: true
  branches:
    include:
      - master
pr:
  - master
schedules:
  - cron: "0 1 * * *"
    displayName: "nightly builds"
    branches:
      include:
        - dev
    always: true
variables:
  - name: yarnCachePath
    value: $(Pipeline.Workspace)/.yarn
  - name: githubRepository
    value: 'timmo001/home-panel'
  - name: dockerSlug
    value: 'home-panel'
  - name: dockerTarget
    value: '.'
  - name: aarch64Base
    value: 'arm64v8/alpine:3.10.3'
  - name: amd64Base
    value: 'amd64/alpine:3.10.3'
  - name: armhfBase
    value: 'arm32v6/alpine:3.10.3'
  - name: armv7Base
    value: 'arm32v7/alpine:3.10.3'
  - name: i386Base
    value: 'i386/alpine:3.10.3'
  - name: versionHadolint
    value: 'v1.17.2'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'timmo001/organization'
      endpoint: 'timmo001'

stages:
  - stage: 'Lint'
    jobs:
      - template: azure-ci/lint-hadolint.yml@azure
        parameters:
          hadolintVersion: $(versionHadolint)
  - stage: 'Build'
    dependsOn: 'Lint'
    condition: succeeded()
    jobs:
      - job: 'Build_App'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Cache@2
            inputs:
              key: 'yarn | "$(Agent.OS)" | yarn.lock'
              path: $(yarnCachePath)
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
            displayName: 'Cache Yarn Packages'
          - task: NodeTool@0
            inputs:
              versionSpec: '13.x'
            displayName: 'Install Node.js'
          - script: |
              yarn install  --pure-lockfile --cache-folder $(yarnCachePath)
              yarn run build --production
            displayName: 'Install and Build'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'build'
              ArtifactName: 'app'
              publishLocation: 'Container'
            displayName: 'Publish Build'
  - stage: 'Docker'
    dependsOn: 'Build'
    condition: succeeded()
    jobs:
      - job: 'Build_Docker'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          maxParallel: 5
          matrix:
            aarch64:
              buildArch: 'aarch64'
              buildBase: $(aarch64Base)
              buildMachine: 'qemuarm-64,raspberrypi3-64,raspberrypi4-64,odroid-c2,orangepi-prime'
            amd64:
              buildArch: 'amd64'
              buildBase: $(amd64Base)
              buildMachine: 'qemux86-64,intel-nuc'
            armhf:
              buildArch: 'armhf'
              buildBase: $(armhfBase)
              buildMachine: 'qemuarm,raspberrypi'
            armv7:
              buildArch: 'armv7'
              buildBase: $(armv7Base)
              buildMachine: 'raspberrypi2,raspberrypi3,raspberrypi4,odroid-xu,tinker'
            i386:
              buildArch: 'i386'
              buildBase: $(i386Base)
              buildMachine: 'qemux86'
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: 'app'
              downloadPath: $(System.DefaultWorkingDirectory)/build
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerHub'
              repository: $(dockerSlug)
              command: 'build'
              Dockerfile: 'Dockerfile'
              arguments: |
                --build-arg "BUILD_ARCH=$(buildArch)"
                --build-arg "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")"
                --build-arg "BUILD_FROM=$(buildBase)"
            displayName: 'Docker Build'
      - job: 'Push_Docker'
        dependsOn: 'Build_Docker'
        condition: succeeded()
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerHub'
              command: 'login'
            displayName: 'Docker Login'
