---
trigger:
  batch: true
  branches:
    include:
      - "master"

pr: "none"

pool: "Default"

variables:
  - group: github

stages:
  - stage: "Docs"
    displayName: "Docs"
    jobs:
      - job: "Docs_MkDocs"
        displayName: "MkDocs"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        steps:
          - script: |
              sudo apt install -y git python3-dev python3-pip python3-setuptools python3-wheel
              python3 -m pip --version
              python3 -m pip install mkdocs mkdocs-material pymdown-extensions
            displayName: "Install"
          - script: |
              git config --global user.email "$(githubEmail)"
              git config --global user.name "Git"
              git status
            displayName: "Setup Git"
          - script: |
              cd docs
              python3 -m mkdocs gh-deploy -v -c -m ":books: Update docs"
            displayName: "MkDocs"
