---
trigger:
  batch: true
  branches:
    include:
      - master

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: github

stages:
  - stage: "Docs"
    displayName: "Docs"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
      - job: "Docs_MkDocs"
        displayName: "MkDocs"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
        steps:
          - script: |
              sudo apt install -y git python3-dev python3-pip
              python3.7 -m pip --version
              python3.7 -m pip install mkdocs mkdocs-material pymdown-extensions
            displayName: "Install"
          - script: |
              cd docs
              python3.7 -m mkdocs gh-deploy -v -c -m "📚 Update docs"
            displayName: "MkDocs"
